# 11 · Leave-one-event-out validation and lead time (Phase M3)
Each flood episode is held out in turn; this is the primary skill estimate.

In [1]:
import os, sys, json, subprocess
from pathlib import Path
ROOT = Path.cwd() if (Path.cwd() / "src").exists() else Path.cwd().parent
os.chdir(ROOT); sys.path.insert(0, str(ROOT))
import pandas as pd
from IPython.display import Image, Markdown, display
pd.set_option("display.width", 200); pd.set_option("display.max_columns", 30)

In [2]:
from src.event_cv import run, lead_times
summary = run()
summary

6 flood episodes: ['2022-08-18', '2022-09-21', '2023-07-12', '2023-08-05', '2023-08-13', '2023-08-20']

{'experiment': 'Exp_A_Rainfall_Only', 'features': 10, 'folds': 6, 'rows': 15035, 'positives': 730, 'pooled_roc_auc': 0.5647, 'pooled_pr_auc': 0.057, 'base_rate': np.float64(0.0486), 'mean_fold_roc_auc': 0.6075, 'min_fold_roc_auc': 0.4233}

{'experiment': 'Exp_B_Rainfall_Discharge', 'features': 14, 'folds': 6, 'rows': 15035, 'positives': 730, 'pooled_roc_auc': 0.5911, 'pooled_pr_auc': 0.1131, 'base_rate': np.float64(0.0486), 'mean_fold_roc_auc': 0.6879, 'min_fold_roc_auc': 0.5655}

{'experiment': 'Exp_C_Rainfall_Discharge_FloodHist', 'features': 21, 'folds': 6, 'rows': 15035, 'positives': 730, 'pooled_roc_auc': 0.7463, 'pooled_pr_auc': 0.2124, 'base_rate': np.float64(0.0486), 'mean_fold_roc_auc': 0.7856, 'min_fold_roc_auc': 0.5679}

{'experiment': 'Exp_D_Rainfall_Discharge_Flood_Landslide', 'features': 25, 'folds': 6, 'rows': 15035, 'positives': 730, 'pooled_roc_auc': 0.7459, 'pooled_pr_auc': 0.2055, 'base_rate': np.float64(0.0486), 'mean_fold_roc_auc': 0.7861, 'min_fold_roc_auc': 0.5679}

{'experiment': 'Exp_E_Full_Multimodal', 'features': 32, 'folds': 6, 'rows': 15035, 'positives': 730, 'pooled_roc_auc': 0.7362, 'pooled_pr_auc': 0.2546, 'base_rate': np.float64(0.0486), 'mean_fold_roc_auc': 0.841, 'min_fold_roc_auc': 0.55}

{'experiment': 'Exp_F_No_Location', 'features': 30, 'folds': 6, 'rows': 15035, 'positives': 730, 'pooled_roc_auc': 0.7364, 'pooled_pr_auc': 0.2545, 'base_rate': np.float64(0.0486), 'mean_fold_roc_auc': 0.8398, 'min_fold_roc_auc': 0.5429}

{'experiment': 'Exp_G_Static_History', 'features': 23, 'folds': 6, 'rows': 15035, 'positives': 730, 'pooled_roc_auc': 0.8583, 'pooled_pr_auc': 0.196, 'base_rate': np.float64(0.0486), 'mean_fold_roc_auc': 0.8619, 'min_fold_roc_auc': 0.8083}

{'experiment': 'Exp_H_Multisource', 'features': 42, 'folds': 6, 'rows': 15035, 'positives': 730, 'pooled_roc_auc': 0.8245, 'pooled_pr_auc': 0.1357, 'base_rate': np.float64(0.0486), 'mean_fold_roc_auc': 0.7796, 'min_fold_roc_auc': 0.4985}

{'experiment': 'Exp_T_Trigger_Only', 'features': 29, 'folds': 6, 'rows': 15035, 'positives': 730, 'pooled_roc_auc': 0.4784, 'pooled_pr_auc': 0.0866, 'base_rate': np.float64(0.0486), 'mean_fold_roc_auc': 0.6192, 'min_fold_roc_auc': 0.3148}

                                 experiment  features  folds   rows  positives  pooled_roc_auc  pooled_pr_auc  base_rate  mean_fold_roc_auc  min_fold_roc_auc
0                       Exp_A_Rainfall_Only        10      6  15035        730          0.5647         0.0570     0.0486             0.6075            0.4233
1                  Exp_B_Rainfall_Discharge        14      6  15035        730          0.5911         0.1131     0.0486             0.6879            0.5655
2        Exp_C_Rainfall_Discharge_FloodHist        21      6  15035        730          0.7463         0.2124     0.0486             0.7856            0.5679
3  Exp_D_Rainfall_Discharge_Flood_Landslide        25      6  15035        730          0.7459         0.2055     0.0486             0.7861            0.5679
4                     Exp_E_Full_Multimodal        32      6  15035        730          0.7362         0.2546     0.0486             0.8410            0.5500
5                         Exp_F_No_Location        30      6  15035        730          0.7364         0.2545     0.0486             0.8398            0.5429
6                      Exp_G_Static_History        23      6  15035        730          0.8583         0.1960     0.0486             0.8619            0.8083
7                         Exp_H_Multisource        42      6  15035        730          0.8245         0.1357     0.0486             0.7796            0.4985
8                        Exp_T_Trigger_Only        29      6  15035        730          0.4784         0.0866     0.0486             0.6192            0.3148

In [3]:
lt = lead_times()
lt

     district event_start  stations  max_p  detected  lead_time_h
     Dehradun  2022-08-19         2  0.729     False          NaN
     Dehradun  2022-09-22         3  0.730     False          NaN
   Uttarkashi  2022-09-22         1  0.571     False          NaN
     Dehradun  2023-07-09         1  0.774      True          0.0
   Uttarkashi  2023-07-10         1  0.706     False          NaN
  Pithoragarh  2023-07-11         3  0.184     False          NaN
      Chamoli  2023-07-16         3  0.184     False          NaN
Tehri Garhwal  2023-08-06         1  0.781      True         48.0
     Dehradun  2023-08-14         2  0.741      True         48.0
Tehri Garhwal  2023-08-14         1  0.786      True         48.0
Tehri Garhwal  2023-08-21         1  0.771      True         48.0
{'experiment': 'Exp_G_Static_History', 'alarm_threshold': 0.7304, 'hourly_false_alarm_rate': 0.05, 'events_evaluated': 11, 'events_detected': 5, 'median_lead_time_h': 48.0}

         district event_start  stations  max_p  detected  lead_time_h
0        Dehradun  2022-08-19         2  0.729     False          NaN
1        Dehradun  2022-09-22         3  0.730     False          NaN
2      Uttarkashi  2022-09-22         1  0.571     False          NaN
3        Dehradun  2023-07-09         1  0.774      True          0.0
4      Uttarkashi  2023-07-10         1  0.706     False          NaN
5     Pithoragarh  2023-07-11         3  0.184     False          NaN
6         Chamoli  2023-07-16         3  0.184     False          NaN
7   Tehri Garhwal  2023-08-06         1  0.781      True         48.0
8        Dehradun  2023-08-14         2  0.741      True         48.0
9   Tehri Garhwal  2023-08-14         1  0.786      True         48.0
10  Tehri Garhwal  2023-08-21         1  0.771      True         48.0